site:
  title: ZUGFeRD Info
  start_page: e-invoicing::index.adoc
content:
  sources:
  - url: https://github.com/ZUGFeRD/ZUGFeRD.github.io.git
    branches: HEAD
ui:
  bundle:
    url: https://github.com/ZUGFeRD/ZUGFeRD.github.io/raw/master/docs-site/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
antora:
  extensions:
    - require: '@antora/lunr-extension'
